services:
  - type: web
    name: personality-trait-app
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.10
